{{ if .Values.rbac.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-secrets-store-provider-alibabacloud
  namespace: {{ .Release.Namespace }}
{{ include "csspa.labels" . | indent 2 }}
{{ end }}
