{{- if .Values.rbac.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-secrets-store-provider-alibabacloud
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "csspa.labels" . | nindent 4 }}
{{- end }}
