apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-secrets-store-provider-alibabacloud
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: csi-secrets-store-provider-alibabacloud
  name: csi-secrets-store-provider-alibabacloud
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: csi-secrets-store-provider-alibabacloud
  template:
    metadata:
      labels:
        app: csi-secrets-store-provider-alibabacloud
    spec:
      serviceAccountName: csi-secrets-store-provider-alibabacloud
      hostNetwork: true
      containers:
        - name: provider-alibabacloud-installer
          image: registry.cn-hangzhou.aliyuncs.com/acs/csi-secrets-store-provider-alibabacloud:v0.1.0
          imagePullPolicy: IfNotPresent
          args:
            - --endpoint=unix:///provider/alibabacloud.sock
            - --healthz-port=8989
            - --healthz-path=/healthz
            - --healthz-timeout=5s
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8989
            failureThreshold: 3
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 30
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 50m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 0
            capabilities:
              drop:
              - ALL
          volumeMounts:
            - mountPath: "/provider"
              name: provider
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
      volumes:
        - name: provider
          hostPath:
            path: "/var/run/secrets-store-csi-providers"
      nodeSelector:
        kubernetes.io/os: linux
