apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: test-secrets
spec:
  provider: alibabacloud   # please using fixed value 'alibabacloud'
  parameters:
    objects: |
      - objectName: "test"
