apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: test-secrets
spec:
  provider: alibabacloud # please using fixed value 'alibabacloud'
  parameters:
    objects: | # objectType support kms and oos, default is kms
      - objectName: "test-kms"
        objectType: "kms"
      - objectName: "test-oos"
        objectType: "oos"
