apiVersion: v1
name: csi-secrets-store-provider-alibabacloud
version: 0.1.0
appVersion: 0.1.0
kubeVersion: ">=1.16.0-0"
description: A Helm chart to install the Secrets Store CSI Driver and the Alibaba Cloud KMS Secret Manager Provider inside a Kubernetes cluster.
sources:
  - https://github.com/AliyunContainerService/secrets-store-csi-driver-provider-alibabacloud
home: https://github.com/AliyunContainerService/secrets-store-csi-driver-provider-alibabacloud
dependencies:
- name: secrets-store-csi-driver
  repository: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
  version: 1.2.4
  condition: secrets-store-csi-driver.install