apiVersion: v1
name: csi-secrets-store-provider-alibabacloud
version: 0.6.0
appVersion: 0.6.0
kubeVersion: ">=1.30.0-0"
description: A Helm chart for deploying the Secrets Store CSI Driver Provider for Alibaba Cloud, supporting multiple authentication methods including AK/SK, RAM Role, RRSA/OIDC, ECS RAM Role, and Node Publish Secret.
sources:
  - https://github.com/AliyunContainerService/secrets-store-csi-driver-provider-alibaba-cloud
home: https://github.com/AliyunContainerService/secrets-store-csi-driver-provider-alibaba-cloud
keywords:
  - releaseName:csi-secrets-store-provider-alibabacloud
  - arch:amd64
  - namespace:kube-system
  - supportType:ExternalKubernetes,Kubernetes,ManagedKubernetes
dependencies:
  - name: secrets-store-csi-driver
    repository: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
    version: 1.6.0
    condition: secrets-store-csi-driver.install
