apiVersion: v1
name: csi-secrets-store-provider-alibabacloud
version: 0.3.0
appVersion: 0.3.0
kubeVersion: ">=1.16.0-0"
description: A Helm chart to install the Secrets Store CSI Driver, the Alibaba Cloud KMS Secret Manager and OOS Eencrypted Parameter Provider inside a Kubernetes cluster.
sources:
  - https://github.com/AliyunContainerService/secrets-store-csi-driver-provider-alibabacloud
home: https://github.com/AliyunContainerService/secrets-store-csi-driver-provider-alibabacloud
keywords:
  - releaseName:csi-secrets-store-provider-alibabacloud
  - arch:amd64
  - namespace:kube-system
  - supportType:ExternalKubernetes,Kubernetes,ManagedKubernetes
dependencies:
  - name: secrets-store-csi-driver
    repository: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
    version: 1.4.6
    condition: secrets-store-csi-driver.install
